import { useState, useEffect, useMemo, useRef } from "react";
import {
  FiArrowLeft,
  FiSave,
  FiCalendar,
  FiRefreshCw,
  FiInfo,
} from "react-icons/fi";
import { usePreviewAvailability } from "../../../queries/providerAvailabilities";
import Loader from "../../../common/Loader";
import SlotCalendar from "./SlotCalendar";

const Step4Preview = ({
  onBack,
  formData,
  previewData,
  setPreviewData,
  onSave,
  isSaving,
  isEdit = false,
}) => {
  const [viewMode, setViewMode] = useState("list");
  const previewMutation = usePreviewAvailability();

  // Auto-generate only for edit mode, only ONCE
  const autoGeneratedRef = useRef(false);

  // Snapshot of config that preview was generated from
  const [previewSnapshot, setPreviewSnapshot] = useState(null);

  // Compute current payload from formData
  const currentPayload = useMemo(
    () => ({
      admin_id: formData.provider_id?.value,
      appointment_type_id: formData.appointment_type_id?.value,
      date_from: formData.date_from,
      date_to: formData.date_to,
      days_of_week: formData.days_of_week,
      start_time: formData.start_time,
      end_time: formData.end_time,
      slot_duration: formData.slot_duration,
      capacity: formData.capacity,
    }),
    [formData],
  );

  // Check if config changed since preview was generated
  const configChanged = useMemo(() => {
    if (!previewSnapshot) return false;
    return JSON.stringify(previewSnapshot) !== JSON.stringify(currentPayload);
  }, [previewSnapshot, currentPayload]);

  // Auto-generate preview for edit mode — once
  useEffect(() => {
    if (!isEdit) return;
    if (autoGeneratedRef.current) return;
    if (previewData) {
      // Already has data (from a previous visit in this session)
      autoGeneratedRef.current = true;
      return;
    }
    if (!formData.provider_id?.value) return;
    if (!formData.appointment_type_id?.value) return;

    autoGeneratedRef.current = true;
    previewMutation.mutate(currentPayload, {
      onSuccess: (data) => {
        setPreviewData(data.data);
        setPreviewSnapshot(currentPayload);
      },
    });
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [
    isEdit,
    formData.provider_id?.value,
    formData.appointment_type_id?.value,
  ]);

  const generatePreview = () => {
    previewMutation.mutate(currentPayload, {
      onSuccess: (data) => {
        setPreviewData(data.data);
        setPreviewSnapshot(currentPayload);
      },
    });
  };

  const summary = previewData?.summary;
  const dates = previewData?.dates || [];

  const handleSave = () => {
    onSave({ ...currentPayload, status: true });
  };

  const showGenerateButton = !previewData || configChanged;
  const isGenerating = previewMutation.isPending;

  return (
    <div className="space-y-5">
      <div>
        <h3 className="font-jakarta text-base font-bold text-ink-900">
          Preview & Save
        </h3>
        <p className="mt-1 text-sm text-ink-500">
          Review generated slots before saving the availability.
        </p>
      </div>

      {/* Generating state */}
      {isGenerating && (
        <div className="rounded-lg border border-accent-200 bg-accent-50/50 px-4 py-3">
          <div className="flex items-center gap-2">
            <FiRefreshCw className="h-4 w-4 animate-spin text-accent-700" />
            <p className="text-xs font-medium text-accent-800">
              Generating preview with current configuration...
            </p>
          </div>
        </div>
      )}

      {/* Config changed warning */}
      {configChanged && previewData && !isGenerating && (
        <div className="rounded-lg border border-warn-200 bg-warn-50/50 px-4 py-3">
          <div className="flex items-start gap-2">
            <FiInfo className="mt-0.5 h-4 w-4 shrink-0 text-warn-700" />
            <div className="min-w-0 flex-1">
              <p className="text-xs font-semibold text-warn-900">
                Configuration has changed
              </p>
              <p className="mt-0.5 text-[11px] text-warn-800">
                You've modified the schedule since the last preview. Click{" "}
                <strong>Regenerate Preview</strong> to see updated slots.
              </p>
            </div>
          </div>
        </div>
      )}

      {/* Generate / Regenerate button */}
      {showGenerateButton && !isGenerating && (
        <button
          type="button"
          onClick={generatePreview}
          className="inline-flex cursor-pointer items-center gap-2 rounded-lg bg-accent-600 px-4 py-2.5 text-sm font-semibold text-surface hover:bg-accent-700"
        >
          <FiCalendar className="h-4 w-4" />
          {previewData ? "Regenerate Preview" : "Generate Preview"}
        </button>
      )}

      {previewData && summary && (
        <>
          {/* Summary Card */}
          <div className="rounded-lg border border-ink-100 bg-ink-50/40 p-4">
            <div className="grid grid-cols-2 gap-4 sm:grid-cols-4">
              <div>
                <p className="text-[11px] text-ink-500">Provider</p>
                <p className="text-sm font-semibold text-ink-900">
                  {summary.provider?.name}
                </p>
                <p className="text-[11px] text-ink-500">
                  {summary.provider?.role_label}
                </p>
              </div>
              <div>
                <p className="text-[11px] text-ink-500">Appointment Type</p>
                <p className="text-sm font-semibold text-ink-900">
                  {summary.appointment_type?.name}
                </p>
              </div>
              <div>
                <p className="text-[11px] text-ink-500">Period</p>
                <p className="text-sm font-semibold text-ink-900">
                  {summary.date_from} → {summary.date_to}
                </p>
              </div>
              <div>
                <p className="text-[11px] text-ink-500">Time</p>
                <p className="text-sm font-semibold text-ink-900">
                  {summary.start_time} - {summary.end_time}
                </p>
              </div>
              <div>
                <p className="text-[11px] text-ink-500">Slot Duration</p>
                <p className="text-sm font-semibold text-ink-900">
                  {summary.slot_duration} Minutes
                </p>
              </div>
              <div>
                <p className="text-[11px] text-ink-500">Capacity</p>
                <p className="text-sm font-semibold text-ink-900">
                  {summary.capacity} Patient
                  {summary.capacity > 1 ? "s" : ""}
                </p>
              </div>
              <div>
                <p className="text-[11px] text-ink-500">Working Days</p>
                <p className="text-sm font-semibold text-ink-900">
                  {summary.total_dates} day{summary.total_dates > 1 ? "s" : ""}
                </p>
              </div>
              <div>
                <p className="text-[11px] text-ink-500">Total Slots</p>
                <p className="text-sm font-semibold text-brand-700">
                  {summary.total_slots} slots
                </p>
              </div>
            </div>
          </div>

          {/* View toggle */}
          <div className="flex gap-2">
            <button
              type="button"
              onClick={() => setViewMode("list")}
              className={`cursor-pointer rounded-lg border px-3 py-1.5 text-xs font-medium transition ${
                viewMode === "list"
                  ? "border-brand-600 bg-brand-50 text-brand-700"
                  : "border-ink-200 bg-surface text-ink-600 hover:bg-ink-50"
              }`}
            >
              List View
            </button>
            <button
              type="button"
              onClick={() => setViewMode("calendar")}
              className={`cursor-pointer rounded-lg border px-3 py-1.5 text-xs font-medium transition ${
                viewMode === "calendar"
                  ? "border-brand-600 bg-brand-50 text-brand-700"
                  : "border-ink-200 bg-surface text-ink-600 hover:bg-ink-50"
              }`}
            >
              Calendar View
            </button>
          </div>

          {/* Preview content */}
          {viewMode === "list" ? (
            <div className="max-h-[400px] space-y-4 overflow-y-auto rounded-lg border border-ink-100 bg-surface p-4">
              {dates.map((dateItem) => (
                <div key={dateItem.date}>
                  <div className="mb-2 flex items-center justify-between">
                    <p className="text-sm font-semibold text-ink-900">
                      {dateItem.day}, {dateItem.date}
                    </p>
                    <span className="rounded-full bg-ink-100 px-2 py-0.5 text-[10px] font-medium text-ink-600">
                      {dateItem.total_slots} slots
                    </span>
                  </div>
                  <div className="grid grid-cols-2 gap-2 sm:grid-cols-4">
                    {dateItem.slots.map((slot, idx) => (
                      <div
                        key={idx}
                        className={`rounded-md border px-2.5 py-1.5 text-[11px] font-medium ${
                          slot.selected
                            ? "border-brand-200 bg-brand-50 text-brand-700"
                            : "border-danger-100 bg-danger-50 text-danger-700"
                        }`}
                      >
                        {slot.start_time} - {slot.end_time}
                      </div>
                    ))}
                  </div>
                </div>
              ))}
            </div>
          ) : (
            <SlotCalendar dates={dates} />
          )}
        </>
      )}

      {/* Actions */}
      <div className="flex justify-between gap-3 border-t border-ink-100 pt-4">
        <button
          type="button"
          onClick={onBack}
          className="inline-flex cursor-pointer items-center gap-2 rounded-lg border border-ink-200 px-4 py-2 text-sm font-medium text-ink-700 hover:bg-ink-50"
        >
          <FiArrowLeft className="h-4 w-4" />
          Back
        </button>
        {previewData && !configChanged && (
          <button
            type="button"
            onClick={handleSave}
            disabled={isSaving}
            className={`inline-flex items-center gap-2 rounded-lg px-5 py-2 text-sm font-semibold transition ${
              isSaving
                ? "cursor-wait bg-ink-100 text-ink-500"
                : "cursor-pointer bg-brand-600 text-surface hover:bg-brand-700"
            }`}
          >
            <FiSave className="h-4 w-4" />
            {isSaving ? "Saving..." : "Save Availability"}
          </button>
        )}
      </div>
    </div>
  );
};

export default Step4Preview;
